<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hitung</name>
   <tag></tag>
   <elementGuidId>01fa0e90-7f85-4856-9b17-fdce46cc4b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-main.px-5.d-block.w-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74032508-a70c-4166-bc88-24b4ff95cb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>564d9535-0084-4ed5-aa85-eb93a1265954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-main px-5 d-block w-100</value>
      <webElementGuid>785d775b-f1d6-4503-858a-3189aa7c8547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung</value>
      <webElementGuid>4e774a56-50a3-46f0-bd2d-2f51a897f71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hitung_harga_button&quot;)/button[@class=&quot;btn btn-main px-5 d-block w-100&quot;]</value>
      <webElementGuid>2995fab9-03a7-463b-8c46-9f5fd5021b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>024ba7d8-88f2-4e3e-92ea-395485611bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9421c90c-7430-4382-9b7a-ca6c34671c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-main px-5 d-block w-100</value>
      <webElementGuid>2a6da385-da74-4755-b1da-47d0792157a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung</value>
      <webElementGuid>146ac9a2-24f0-48ca-af69-e013a33c414f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hitung_harga_button&quot;)/button[@class=&quot;btn btn-main px-5 d-block w-100&quot;]</value>
      <webElementGuid>85a19e64-6829-4e2e-a615-7b3258b9cc0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[4]</value>
      <webElementGuid>2764d441-d90e-413d-b5ff-3b5d0f31d55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hitung_harga_button']/button</value>
      <webElementGuid>b49ae4ba-4fcc-4019-8eed-fe17895392bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangka Waktu'])[2]/following::button[1]</value>
      <webElementGuid>6a5b0bec-621f-46b0-99fa-89fef35980bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Per Bulan'])[2]/following::button[1]</value>
      <webElementGuid>7f610cfc-7a87-4e81-840b-f1b09fb8d4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARI PROPERTI'])[1]/preceding::button[1]</value>
      <webElementGuid>2339d1f7-b4a8-48c1-bc9a-371c2e8bbdba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rumah'])[1]/preceding::button[1]</value>
      <webElementGuid>dbdaea6c-2068-435b-bbc2-324eee6ecbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hitung']/parent::*</value>
      <webElementGuid>a5387a1a-5340-4062-a0ab-bc0cfb80208f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>c9c37065-5f62-4d46-bca4-a23e2cafb918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Hitung' or . = 'Hitung')]</value>
      <webElementGuid>dfadf1ce-faaf-4f47-a7ff-99f6b169245d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
